blueprint:
  name: Christmas Lights
  description: |
    Turns on the christmas lights during December at sunset, turns them off at set time and dims WLED lights.

  domain: automation
  input:
	xmas_lights:
		name: Devices to control
		description: Lights or Switches to be turned on/off
		selector:
			domain: switch
	wled_lights:
		name: WLED devices
		description: Any WLED lights to dim automatically (nightlight mode)
		selector:
			device:
				integration: WLED

    stop_time:
      name: Stop Time
      description: Time at which selected lights will turn off
      selector:
        time:
	sleep_time:
      name: Sleep Time
      description: Time at which WLED devices will start dimming
      selector:
        device:
          integration: WLED

mode: single

trigger:
  - platform: sun
    event: sunset
    offset: '-00:05:00'
  - platform: time
    at: !input stop_time
  - platform: time
    at: !input sleep_time
condition:
  - condition: template
    value_template: '{{ now().strftime(''%m'') == ''12'' }}'
action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.platform == ''sun'' }}'
        sequence:
          - service: switch.turn_on
            data:
              entity_id: !input xmas_lights
          - type: turn_on
            device_id: !input wled_lights
            entity_id: light.wled
            domain: light
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.entity_id == '!input stop_time'
              }}
        sequence:
          - service: switch.turn_off
            data: {}
            entity_id: !input xmas_lights
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.entity_id ==
              '!input sleep_time' }}
        sequence:
          - type: turn_on
            device_id: !input wled_lights
            entity_id: switch.wled_nightlight
            domain: switch
    default: []
