blueprint:
  name: Ikea Zigbee Lightswitch
  description: Toggle light based on Ikea switch
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA remote to use
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
    target_light:
      name: Light
      selector:
        target:
          entity:
            domain: light

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      command: 'on'
      device_ieee: !input remote
  - platform: event
    event_type: zha_event
    event_data:
      command: 'off'
      device_ieee: !input remote
  - platform: event
    event_type: zha_event
    event_data:
      command: move_with_on_off
      device_ieee: !input remote

action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == ''off'' }}'
        sequence:
          - service: light.turn_off
            data: {}
            entity_id: !input target_light
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == ''move_with_on_off'' }}'
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 100
            entity_id: !input target_light
    default:
      - service: light.turn_on
        data: {}
        entity_id: !input target_light
