blueprint:
  name: Entity Unavailable Notification
  description: Sends notification of which entity has lost connection

  domain: automation
  input:
    entity_name:
      name: Entity
      description: Device to check
      selector:
        target:
          entity:
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications
      selector:
        entity:
          domain: notify

mode: queued
max: 10

trigger:
  - entity_id: !input entity_name
    for: '30'
    platform: state
    to: unavailable
action:
  - service: !input notify_device
    data:
      message: '{{ trigger.to_state.name }} disconnected'
