blueprint:
  name: xmas lights
  description: |
    Turns lights on at sunset and off at specific time

  domain: automation
  input:
    name: stop_xmas_time
    selector:
        time:
    xmas_lights:
      name: Light(s)
      description: The light(s) to control
      selector:
        target:
          entity:
            domain: switch

mode: single
max_exceeded: silent

trigger:
  - platform: sun
    event: sunset
    offset: '-00:05:00'

action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.platform == ''sun'' }}'
        sequence:
          - service: switch.turn_on
            data:
              entity_id: !input xmas_lights
