blueprint:
  name: xmas lights
  description: |
    Turns lights on at sunset and off at specific time

  domain: automation
  input:
    stop_time:
      name: Stop Time
      description: Time at which selected lights will turn off
      selector:
        time:
    xmas_lights:
      name: Light(s)
      description: The light(s) to control
      selector:
        target:
          entity:
            domain: switch

mode: single
max_exceeded: silent

trigger:
  - platform: sun
    event: sunset
    offset: '-00:05:00'
  - platform: time
    at: !input stop_time
    
variables:
  stop_time_var: !input stop_time
  
action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.platform == ''sun'' }}'
        sequence:
          - service: switch.turn_on
            data:
              entity_id: !input xmas_lights
      - conditions:
          - condition: template
            value_template: '{{ trigger.platform == ''time'' }}'
        sequence:
          - service: switch.turn_off
            target: !input xmas_lights
